class EyeState:
    IDLE = "idle"
    HAPPY = "happy"
    SAD = "sad"
    SCARE = "scare"
    DISDAIN = "disdain"
    ANGRY = "angry"    
    LOOK_LEFT = "look_left"
    LOOK_RIGHT = "look_right"  
    BLINK = "idle"    
    SLEEP = "idle"
    LISTENING = "idle"
    THINKING = "idle"