class EyeState:
    IDLE = "idle"         
    HAPPY = "happy"
    SAD = "sad"
    ANGRY = "angry"
    DISDAIN = "disdain"
    SCARE = "scare"       
    LISTENING = "idle"   
    THINKING = "idle" 
    SLEEP = "idle"